//
//  SPNotification.swift
//  Chunlangjiu
//
//  Created by 黄树鹏 on 2018/8/5.
//  Copyright © 2018年 Chunlang. All rights reserved.
//

import Foundation

/// 登录成功通知
let SP_LOGIN_NOTIFICATION = "SP_LOGIN_NOTIFICATION"
/// 退出登录通知
let SP_LOGOUT_NOTIFICATION = "SP_LOGOUT_NOTIFICATION"
/// 定位的通知
let SP_LOCATION_NOTIFICATION = "SP_LOCATION_NOTIFICATION"
/// 切换tabbar的通知
let SP_CHANGETABBAR_NOTIIFICATION = "SP_CHANGETABBAR_NOTIIFICATION"
/// 定时器运行时的通知
let SP_TIMERUN_NOTIFICATION = "SP_TIMERUN_NOTIFICATION"
/// 提交竞拍订单的通知
let SP_SUBMITAUCTION_NOTIFICATION = "SP_SUBMITAUCTION_NOTIFICATION"
/// 修改出价成功的通知
let SP_EDITPRICEAUCTON_NOTIFICATION = "SP_EDITPRICEAUCTON_NOTIFICATION"
/// 竞拍结束的通知
let SP_AUCTIONEND_NOTIFICATION = "SP_AUCTIONEND_NOTIFICATION"
/// 切换身份通知
let SP_CHANGEID_NOTIFICATION = "SP_CHANGEID_NOTIFICATION"
