//
//  SPNotification.swift
//  Chunlangjiu
//
//  Created by 黄树鹏 on 2018/8/5.
//  Copyright © 2018年 Chunlang. All rights reserved.
//

import Foundation

/// 登录成功通知
let SP_LOGIN_NOTIFICATION = "SP_LOGIN_NOTIFICATION"
/// 退出登录通知
let SP_LOGOUT_NOTIFICATION = "SP_LOGOUT_NOTIFICATION"
/// 定位的通知
let SP_LOCATION_NOTIFICATION = "SP_LOCATION_NOTIFICATION"
/// 切换tabbar的通知
let SP_CHANGETABBAR_NOTIIFICATION = "SP_CHANGETABBAR_NOTIIFICATION"
/// 定时器运行时的通知
let SP_TIMERUN_NOTIFICATION = "SP_TIMERUN_NOTIFICATION"
/// 提交竞拍订单的通知
let SP_SUBMITAUCTION_NOTIFICATION = "SP_SUBMITAUCTION_NOTIFICATION"
/// 修改出价成功的通知
let SP_EDITPRICEAUCTON_NOTIFICATION = "SP_EDITPRICEAUCTON_NOTIFICATION"
/// 竞拍结束的通知
let SP_AUCTIONEND_NOTIFICATION = "SP_AUCTIONEND_NOTIFICATION"
/// 切换身份通知
let SP_CHANGEID_NOTIFICATION = "SP_CHANGEID_NOTIFICATION"
/// 订单 待付款通知
let SP_ORDER_WAIT_BUYER_PAY_NOTIFICATION = "SP_ORDER_WAIT_BUYER_PAY_NOTIFICATION"
/// 订单 待收货
let SP_ORDER_WAIT_BUYER_CONFIRM_GOODS_NOTIFICATION = "SP_ORDER_WAIT_BUYER_CONFIRM_GOODS_NOTIFICATION"
/// 订单 待发货
let SP_ORDER_WAIT_SELLER_SEND_GOODS_NOTIFICATION = "SP_ORDER_WAIT_SELLER_SEND_GOODS_NOTIFICATION"
/// 订单 已完成
let SP_ORDER_FINISH_NOTIFICATION = "SP_ORDER_FINISH_NOTIFICATION"
/// 订单 全部
let SP_ORDER_ALL_NOTIFICATION = "SP_ORDER_ALL_NOTIFICATION"
/// 订单 竞拍 待付定金
let SP_ORDER_AUCTIIN_PAY = "SP_ORDER_AUCTIIN_PAY"
/// 订单 竞拍中
let SP_ORDER_AUCTION_ING_NOTIFICATION = "SP_ORDER_AUCTION_ING_NOTIFICATION"
/// 订单 所有竞拍订单
let SP_ORDER_AUCTION_ALL_NOTIFICATION = "SP_ORDER_AUCTION_ALL_NOTIFICATION"
/// 审核中的通知
let SP_PRODUCT_REVIEW_NOTIFICATION = "SP_PRODUCT_REVIEW_NOTIFICATION"
